directories:
  output: release
  buildResources: resources
appId: com.homecanvas.app
productName: Home Canvas
files:
  - filter:
      - dist/**
      - electron/**
      - package.json
asar: true
win:
  target:
    - nsis
    - portable
nsis:
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
electronVersion: 31.7.7
